# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HumanitecSetupWizard < Formula
  desc ""
  homepage "https://github.com/humanitec-architecture/setup-wizard"
  version "0.9.0"

  on_macos do
    on_intel do
      url "https://github.com/humanitec-architecture/setup-wizard/releases/download/v0.9.0/setup-wizard_0.9.0_darwin_amd64.tar.gz"
      sha256 "469970a0719fba7b5a6d4b983c94b7b585b5a7356e50c35f7ebf76d1afbccc17"

      def install
        bin.install "humanitec-setup-wizard"
      end
    end
    on_arm do
      url "https://github.com/humanitec-architecture/setup-wizard/releases/download/v0.9.0/setup-wizard_0.9.0_darwin_arm64.tar.gz"
      sha256 "62058585d613544c02514cbee51d2d919879336e7353ac5c7e047fb340184edd"

      def install
        bin.install "humanitec-setup-wizard"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/humanitec-architecture/setup-wizard/releases/download/v0.9.0/setup-wizard_0.9.0_linux_amd64.tar.gz"
        sha256 "9e6e46892c403a96446c3a00aad0c297566e671b043e9b2616c4c510175e876a"

        def install
          bin.install "humanitec-setup-wizard"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/humanitec-architecture/setup-wizard/releases/download/v0.9.0/setup-wizard_0.9.0_linux_arm64.tar.gz"
        sha256 "58fb2ba3525ab0dd93bd06c24863872ad727ee4c14b9b81210204843a5c49fce"

        def install
          bin.install "humanitec-setup-wizard"
        end
      end
    end
  end
end
