# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HumanitecSetupWizard < Formula
  desc ""
  homepage "https://github.com/humanitec-architecture/setup-wizard"
  version "0.13.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/humanitec-architecture/setup-wizard/releases/download/v0.13.3/setup-wizard_0.13.3_darwin_amd64.tar.gz"
      sha256 "a5b87b6b5c96a487c9b3b2f77485e8ad74c7d8e144179b6eab626482c592ce59"

      def install
        bin.install "humanitec-setup-wizard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/humanitec-architecture/setup-wizard/releases/download/v0.13.3/setup-wizard_0.13.3_darwin_arm64.tar.gz"
      sha256 "eb8ee56cc468fc267505096f8bcc046cd4128147a53e9a8befa00f44aba76c25"

      def install
        bin.install "humanitec-setup-wizard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/humanitec-architecture/setup-wizard/releases/download/v0.13.3/setup-wizard_0.13.3_linux_amd64.tar.gz"
        sha256 "18e5ae043527b248d67e3d6224bfb174b0d2446ff8d3aad040f97f8932223d95"

        def install
          bin.install "humanitec-setup-wizard"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/humanitec-architecture/setup-wizard/releases/download/v0.13.3/setup-wizard_0.13.3_linux_arm64.tar.gz"
        sha256 "0c35e407ab7d8b2fe8654c927ace1da6388220c673c0b36fe69aae0a12beb4c9"

        def install
          bin.install "humanitec-setup-wizard"
        end
      end
    end
  end
end
