# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HumanitecSetupWizard < Formula
  desc ""
  homepage "https://github.com/humanitec-architecture/setup-wizard"
  version "0.13.0"

  on_macos do
    on_intel do
      url "https://github.com/humanitec-architecture/setup-wizard/releases/download/v0.13.0/setup-wizard_0.13.0_darwin_amd64.tar.gz"
      sha256 "30e044c0c5d02dc0032294b9c980d3734b43f9911b89e748a9883723418a04fa"

      def install
        bin.install "humanitec-setup-wizard"
      end
    end
    on_arm do
      url "https://github.com/humanitec-architecture/setup-wizard/releases/download/v0.13.0/setup-wizard_0.13.0_darwin_arm64.tar.gz"
      sha256 "b4f993bafd8ed5f3b485c242ba00c481a7a30d93d7a3217416a6e0b1609519fc"

      def install
        bin.install "humanitec-setup-wizard"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/humanitec-architecture/setup-wizard/releases/download/v0.13.0/setup-wizard_0.13.0_linux_amd64.tar.gz"
        sha256 "918ac8259cce91f7161c17cebcc5e9546bda019a34f209a3d5e27456f964fe59"

        def install
          bin.install "humanitec-setup-wizard"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/humanitec-architecture/setup-wizard/releases/download/v0.13.0/setup-wizard_0.13.0_linux_arm64.tar.gz"
        sha256 "ff417eb5957e77a201185e84af5003cced87086c3584beb8472b6cd51362e4a1"

        def install
          bin.install "humanitec-setup-wizard"
        end
      end
    end
  end
end
